apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: excessive
  name: app
  labels:
    app: app
spec:
  replicas: 2
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: excessive:48ae3b3efffd40f73d3470ceb6b985a7ca316b0f
          imagePullPolicy: IfNotPresent
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: excessive
                  key: rails_env
          ports:
            - containerPort: 3000
              name: http
      restartPolicy: Always
  selector:
    matchLabels:
      app: app
