apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: excessive
  name: app
  labels:
    app: app
spec:
  replicas: 2
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: excessive
          imagePullPolicy: IfNotPresent
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: rails_env
          ports:
            - containerPort: 3000
              name: http
      restartPolicy: Always
  selector:
    matchLabels:
      app: app
