apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: excessive
  name: postgres
spec:
  volumeName: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
