apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: excessive
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.0
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: excessive
                  key: postgres_password
      restartPolicy: Always
  selector:
    matchLabels:
      app: postgres
