apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: excessive
spec:
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30009
      name: http
  type: NodePort
